# Generated by Django 4.2.3 on 2023-07-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('phonenumber', models.IntegerField()),
                ('email', models.CharField(max_length=300)),
                ('messages', models.TextField(max_length=200)),
            ],
        ),
    ]
